
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 106
#define YY_END_OF_BUFFER 107
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[468] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   94,   94,    0,    0,
      100,  100,    0,    0,  107,  105,  103,  104,  105,   14,
       15,   16,   17,  105,  105,   18,   62,   61,   77,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   71,   72,  103,    6,  105,
      105,   13,   13,   13,   13,   13,   13,   66,   66,   66,
       66,   64,   66,   66,   63,   66,   66,   70,   70,   70,
       70,   70,   70,   67,   68,   70,   70,   76,   76,   76,
       76,   76,   76,   73,   74,   76,   76,   80,   80,   80,

       80,   80,   78,   80,   79,   80,   80,    4,    4,    4,
        4,    4,    4,    4,    4,    4,   17,   71,   72,   94,
       95,   97,   94,   96,   94,   88,   88,   89,   87,   86,
       87,   87,   87,   85,  100,  100,  102,   59,  105,  105,
       57,   58,   59,   59,   59,  105,   59,  103,    0,   20,
        0,    0,    0,   99,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,  103,    6,    0,
        6,    5,    0,   98,    0,    0,   12,    0,    0,    0,
        0,    0,   65,    0,    0,    0,  103,    0,   69,    0,

        0,    0,    0,   75,    0,    0,    0,    0,   80,    0,
        0,    0,    0,    3,    0,    0,    0,    1,    2,   94,
       95,   97,    0,    0,   94,   96,   96,   96,   93,    0,
       94,   87,   86,   87,   87,   85,   86,   85,  100,  100,
        0,    0,    0,   60,    0,    0,    0,   59,   59,   19,
       84,   83,   84,   99,   99,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   50,   61,
       61,   61,   29,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,    0,   98,   82,   81,
       82,   98,   98,    0,    0,    0,    0,   65,   69,   75,

       80,    3,    0,   92,   93,   86,   85,  101,   60,   83,
       61,   61,   61,   61,   61,   61,   21,   61,   26,   61,
       61,   37,   61,   61,   51,   61,   61,   31,   53,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   30,   61,
       82,   81,   82,   98,   98,   81,    0,   11,    0,    0,
        0,    0,    0,    0,   92,  101,  101,   61,   61,   61,
       61,   61,   61,   49,   40,   61,   61,   28,   61,   61,
       61,   61,   32,   61,   61,   61,   61,   39,   61,   61,
       81,    0,    0,    0,    0,   61,   61,   61,   61,   61,
       61,   27,   22,   46,   61,   54,   61,   33,   24,   38,

       61,   61,   61,    0,    0,    0,   91,   90,   91,   61,
       42,   61,   61,   61,   61,   61,   61,   25,   61,   61,
        0,    0,    0,   90,   61,   61,   61,   48,   35,   61,
       61,   23,   36,   43,    7,    0,    0,    0,    0,   61,
       41,   61,   61,   61,   61,   52,    7,    0,    0,    0,
       10,   61,   61,   47,   34,   45,    8,    9,   61,   61,
       61,   61,   61,   44,   56,   55,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    7,    1,    8,    9,
       10,   11,    1,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       22,   23,   24,    1,   25,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   21,   21,   35,   36,   37,
       38,   39,   21,   40,   41,   42,   43,   44,   21,   45,
       46,   21,   47,    1,   48,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    1,    1,    1,
        5,    1,    1,    1,    6,    7,    1,    1,    1,    8,
        9,    1,    1,    1,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    1,    1
    } ;

static const flex_int16_t yy_base[514] =
    {   0,
        0,   47,   48,   55,   89,  135,  181,  228,  275,  322,
      369,  392,   64,  415,  437,   58,   96,  114,   72,  117,
      120,  127,  485,   63, 1155, 1156,   59, 1156,   65, 1156,
     1156, 1156, 1156, 1140,   70, 1156, 1156,    0, 1156, 1128,
     1109,  113, 1113,   58,   70, 1107, 1112, 1110, 1117, 1120,
     1115,  111, 1098, 1106, 1104, 1156, 1156,  153, 1139, 1092,
       99, 1156,  109,  132, 1109, 1101, 1103, 1156,  152,  103,
      141, 1156,  150,    0, 1156,  158,  152, 1156,  167,  165,
      158,  161,    0, 1156, 1156,  175,  163, 1156,  189,  175,
      179,  184,    0, 1156, 1156,  190,  186, 1156,  204,  195,

      199,  198, 1156,    0, 1156,  208,  200, 1156,  212,  198,
      211,  209,    0,  223,  210,  224, 1156, 1156, 1156,    0,
      242, 1156,  238,  237,  247, 1156,  245, 1156, 1156,  270,
     1156,  260,  252,  271,    0,  266,  269,  285,  236,  280,
     1156, 1156, 1156, 1120,    0,    0,  289,  290,  290, 1156,
        0, 1121,  295,  327,    0,  313, 1092, 1103, 1106, 1094,
     1087, 1086, 1086, 1087, 1088, 1093,  265, 1087, 1097, 1081,
     1089, 1082, 1087,  270, 1079,  268,   21,  313, 1115,  254,
     1114, 1156,  342,  347, 1112,  329, 1156,  348, 1083, 1085,
     1075,  313, 1156,    0,  293,  297,  361,  362, 1156,    0,

      325,  360,  375, 1156,    0,  367,  378,  376, 1156,    0,
      379,  380,  401, 1156,    0,  381,  402, 1156, 1156,    0,
      424, 1156,  435,  440,  407,  341,  450,  451,  309,  460,
      461, 1156,  532,  427,  466,  533, 1109, 1108,    0,  430,
      406, 1094,  453, 1156,    0,  459,  529, 1092,    0, 1156,
     1156, 1105,  538, 1104,  543, 1063, 1066, 1058, 1065, 1067,
     1062, 1061, 1070, 1057, 1055, 1068, 1058, 1063,    0, 1066,
     1061, 1056, 1059, 1056, 1047, 1058, 1051, 1044, 1046, 1040,
     1038, 1050, 1041, 1044, 1048, 1050,  548,  553, 1156, 1073,
      558, 1072,  563, 1070, 1038, 1036, 1040,  530,  562,  565,

      567,  571,  376,  442,  410, 1067, 1066,  578,  573, 1065,
     1024, 1028, 1022, 1028, 1030, 1026,    0, 1025,    0, 1017,
     1023,    0, 1017, 1014,    0, 1018, 1014,    0,    0, 1027,
     1011, 1009, 1020, 1015, 1020, 1018, 1009, 1013,    0, 1002,
     1156, 1041,  590, 1040,  593, 1039, 1037, 1156, 1002,  995,
     1035,  584, 1025,  453, 1156, 1033,  600,  994,  992, 1002,
      997,  993, 1003,    0,    0,  988,  968,    0,  970,  957,
      961,  953,    0,  965,  965,  950,  957,    0,  932,  926,
      949,  909,  906,  319,  596,  893,  867,  854,  847,  852,
      839,    0,    0,    0,  830,    0,  834,    0,    0,    0,

      815,  807,  784,  808,  762,  431, 1156,  781,  603,  738,
      731,  693,  602,  602,  596,  590,  588,    0,  598,  596,
      623,  582,  537,  622,  580,  597,  587,  593,  591,  575,
      541,    0,    0,    0,    0,  615,    0,    0,  560,  504,
        0,  503,  458,  453,  406,    0,    0,  400,  362,  356,
     1156,  269,  200,    0,    0,  201, 1156, 1156,  150,  116,
       77,   61,   55,    0,    0,    0, 1156,  633,  642,  651,
      660,  669,  678,  687,  696,  705,  714,  723,  726,  735,
      744,  753,  762,  771,  780,  789,  798,  807,  816,  825,
      834,  843,  852,  861,  870,  879,  888,  897,  906,  915,

      924,  927,  936,  945,  954,  963,  972,  981,  989,  992,
     1001, 1010, 1019
    } ;

static const flex_int16_t yy_def[514] =
    {   0,
      467,    1,  468,  468,  469,  469,  470,  470,  471,  471,
      472,  472,  473,  473,  471,   15,  474,  474,  475,  476,
      477,  477,  467,   23,  467,  467,  467,  467,  478,  467,
      467,  467,  467,  467,  467,  467,  467,  479,  467,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  467,  467,  467,  467,  467,
      467,  467,  467,  480,  467,  467,  467,  467,  467,  481,
      482,  467,  467,  483,  467,  467,  467,  467,  467,  484,
      485,  467,  486,  467,  467,  467,  467,  467,  467,  487,
      488,  467,  489,  467,  467,  467,  467,  467,  467,  490,

      491,  467,  467,  492,  467,  467,  467,  467,  467,  493,
      494,  467,  495,  467,  467,  467,  467,  467,  467,  496,
      467,  467,  496,  497,  496,  467,  467,  467,  467,  498,
      467,  467,  498,  498,  499,  499,  467,  467,  500,  501,
      467,  467,  467,  467,  502,  503,  467,  467,  478,  467,
      478,  467,  504,  467,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  467,  467,  467,
      467,  467,  505,  467,  480,  480,  467,  480,  467,  467,
      467,  481,  467,  481,  482,  482,  467,  484,  467,  484,

      485,  485,  487,  467,  487,  488,  488,  490,  467,  490,
      491,  491,  493,  467,  493,  494,  494,  467,  467,  496,
      467,  467,  467,  467,  496,  497,  497,  497,  467,  467,
      496,  467,  498,  467,  498,  498,  467,  467,  499,  499,
      467,  467,  500,  467,  500,  501,  501,  467,  502,  467,
      467,  467,  504,  467,  467,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  506,  467,  467,  467,
      505,  467,  467,  507,  467,  467,  467,  482,  485,  488,

      491,  494,  467,  467,  467,  467,  467,  467,  501,  467,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      467,  467,  506,  467,  467,  467,  507,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      467,  467,  467,  467,  508,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  467,  467,  467,  467,  467,  508,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      509,  467,  467,  467,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  510,  467,  511,  512,  513,  479,
      479,  479,  479,  479,  479,  479,  510,  511,  512,  513,
      467,  479,  479,  479,  479,  479,  467,  467,  479,  479,
      479,  479,  479,  479,  479,  479,    0,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467
    } ;

static const flex_int16_t yy_nxt[1205] =
    {   0,
       26,   27,   28,   27,   29,   26,   26,   26,   30,   31,
       32,   33,   26,   34,   35,   26,   36,   26,   37,   26,
       38,   39,   26,   26,   40,   41,   38,   42,   43,   44,
       45,   38,   46,   47,   48,   38,   49,   38,   50,   51,
       52,   53,   54,   55,   38,   38,   56,   57,   58,   63,
       28,   63,   59,   60,  285,  286,   63,   28,   63,   96,
      148,   61,  148,   64,  147,  109,   28,  109,  110,  150,
       64,  111,   97,  127,  128,  127,   65,   61,  112,  466,
      153,   66,   67,   65,  154,  465,  113,  151,   66,   67,
       69,   28,   69,   70,  162,  164,   71,  121,  122,  123,

       72,  464,  163,   73,  165,   72,  124,  193,  125,  183,
      148,   74,  148,  184,  125,  121,  122,  123,  130,  131,
      132,  136,  137,  136,  124,  194,  125,  133,  136,  137,
      136,  134,  125,  186,  187,   75,   76,   28,   69,   70,
      463,  158,   71,  172,  173,  159,   72,  188,  193,   77,
      160,   72,  174,  148,  178,  148,  148,   74,  179,  197,
      153,  148,  183,  196,  154,  199,  184,  180,  148,  199,
      148,  153,  180,  183,  462,  154,  197,  184,  148,  204,
      202,   75,   79,   28,   79,   80,  204,  200,   81,  180,
      148,  197,  148,  148,  153,   82,  183,  205,  154,  209,

      184,  207,  214,   83,  180,  148,  209,  148,  153,  197,
      183,  148,  154,  148,  184,  148,  218,  210,  214,  153,
      215,  212,  180,  154,  197,  461,  148,   84,   85,   86,
       28,   79,   80,  217,  183,   81,  460,  180,  184,  148,
      244,  225,   87,  221,  222,  148,  148,  227,  148,  228,
       83,  229,  223,  237,  224,  228,  219,  230,  245,  231,
      224,  148,  235,  148,  287,  231,  467,  240,  288,  240,
      241,  233,  238,  234,   84,   85,   89,   28,   89,   90,
      235,  235,   91,  242,  236,  236,  148,  244,  148,   92,
      197,  148,  148,  148,  150,  280,  252,   93,  459,  272,

      193,  283,  247,  180,  298,  253,  273,  253,  284,  281,
      303,  304,  151,  253,  178,  196,  148,  193,  179,  196,
      384,   94,   95,   96,   28,   89,   90,  180,  254,   91,
      186,  187,  199,  294,  406,  194,   97,  255,  256,  255,
      257,  255,  258,  290,   93,  255,  259,  202,  292,  186,
      187,  467,  291,  260,  291,  467,  261,  293,  451,  293,
      291,  293,  197,  188,  148,  293,  199,  299,   94,   95,
       99,   28,   99,  100,  204,  180,  101,  303,  304,  204,
      209,  458,  202,  102,  200,  300,  209,  301,  214,  207,
      103,  104,  105,  106,   28,   99,  100,  205,  210,  101,

      207,  212,  212,  217,  457,  214,  107,  241,  148,  302,
      225,  354,  355,  103,  104,  105,  114,   28,  109,  110,
      242,  115,  111,  215,  217,  221,  222,  148,  148,  116,
      148,  240,  423,  240,  223,  456,  224,  113,   89,   28,
       89,   90,  224,  352,   91,  223,  406,  224,  117,  229,
      230,   92,  224,  224,  354,  355,  353,  244,  224,   93,
      227,  230,  228,  228,  229,  467,  244,  237,  228,  228,
      230,  230,  224,  231,  305,  245,  235,  455,  224,  231,
      467,  247,  454,  118,  119,   26,  138,   28,   27,  139,
       26,   26,  140,  141,  142,   26,  143,   26,   26,   35,

      144,   26,   26,   26,   26,  145,   26,  146,   26,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,   26,   26,  233,  238,  234,  309,  193,  423,  252,
      453,  439,  235,  235,  254,  452,  236,  236,  253,  342,
      253,  247,  196,  255,  344,  255,  253,  255,  343,  290,
      343,  255,  451,  345,  292,  345,  343,  345,  291,  199,
      291,  345,  204,  293,  209,  293,  291,  293,  214,  356,
      244,  293,  446,  436,  202,  352,  437,  207,  357,  212,
      357,  342,  357,  217,  344,  247,  357,  408,  353,  438,

      343,  356,  343,  345,  408,  345,  409,  345,  343,  445,
      357,  345,  357,  409,  357,  444,  436,  443,  357,  437,
      442,  441,  440,  424,  421,  434,  433,  432,  431,  430,
      429,  428,  438,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   98,
       98,   98,   98,   98,   98,   98,   98,   98,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  126,  126,  126,  126,

      126,  126,  126,  126,  126,  129,  129,  129,  129,  129,
      129,  129,  129,  129,  135,  135,  135,  135,  135,  135,
      135,  135,  135,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  155,  427,  155,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  195,  195,  426,  195,  195,  195,  195,
      195,  195,  193,  193,  425,  193,  193,  193,  193,  193,
      193,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      201,  201,  424,  201,  201,  201,  201,  201,  201,  199,
      199,  422,  199,  199,  199,  199,  199,  199,  203,  203,

      203,  203,  203,  203,  203,  203,  203,  206,  206,  421,
      206,  206,  206,  206,  206,  206,  204,  204,  420,  204,
      204,  204,  204,  204,  204,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  211,  211,  419,  211,  211,  211,
      211,  211,  211,  209,  209,  418,  209,  209,  209,  209,
      209,  209,  213,  213,  213,  213,  213,  213,  213,  213,
      213,  216,  216,  417,  216,  216,  216,  216,  216,  216,
      214,  214,  416,  214,  214,  214,  214,  214,  214,  220,
      415,  414,  220,  413,  220,  220,  220,  220,  226,  226,
      412,  226,  226,  226,  226,  226,  226,  232,  232,  232,

      232,  232,  232,  232,  232,  232,  239,  239,  411,  239,
      239,  239,  239,  239,  239,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  246,  246,  410,  246,  246,  246,
      246,  246,  246,  249,  405,  249,  244,  244,  404,  244,
      244,  244,  244,  244,  244,  251,  251,  251,  251,  251,
      381,  251,  251,  251,  289,  289,  289,  289,  289,  403,
      289,  289,  289,  341,  341,  341,  341,  341,  402,  341,
      341,  341,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  407,  407,  407,  407,  407,  401,  407,  407,  407,
      435,  400,  399,  398,  397,  396,  395,  435,  447,  394,

      447,  448,  448,  448,  393,  448,  448,  448,  448,  448,
      449,  449,  449,  449,  449,  449,  449,  392,  449,  450,
      450,  450,  450,  450,  450,  450,  450,  450,  391,  390,
      389,  388,  387,  386,  356,  385,  384,  383,  382,  348,
      346,  344,  381,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  310,  307,  306,  351,
      350,  349,  348,  292,  346,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  330,  329,  328,  327,  326,
      325,  324,  323,  322,  321,  320,  319,  318,  317,  316,

      315,  314,  313,  312,  311,  254,  310,  248,  308,  307,
      306,  297,  296,  295,  187,  181,  181,  282,  279,  278,
      277,  276,  275,  274,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  250,  248,  191,  190,  189,  182,
      181,  177,  176,  175,  171,  170,  169,  168,  167,  166,
      161,  157,  156,  152,  467,   25,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467
    } ;

static const flex_int16_t yy_chk[1205] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        3,    3,    2,    2,  177,  177,    4,    4,    4,   16,
       27,    2,   27,    3,   24,   13,   13,   13,   13,   29,
        4,   13,   16,   19,   19,   19,    3,   24,   13,  463,
       35,    3,    3,    4,   35,  462,   13,   29,    4,    4,
        5,    5,    5,    5,   44,   45,    5,   17,   17,   17,

        5,  461,   44,    5,   45,    5,   17,   70,   17,   61,
       63,    5,   63,   61,   17,   18,   18,   18,   20,   20,
       20,   21,   21,   21,   18,   70,   18,   20,   22,   22,
       22,   20,   18,   64,   64,    5,    6,    6,    6,    6,
      460,   42,    6,   52,   52,   42,    6,   64,   71,    6,
       42,    6,   52,   69,   58,   69,   58,    6,   58,   76,
       73,   76,   77,   71,   73,   81,   77,   58,   79,   80,
       79,   82,   76,   87,  459,   82,   86,   87,   86,   90,
       81,    6,    7,    7,    7,    7,   91,   80,    7,   86,
       89,   96,   89,   96,   92,    7,   97,   90,   92,  100,

       97,   91,  110,    7,   96,   99,  101,   99,  102,  106,
      107,  106,  102,  109,  107,  109,  115,  100,  111,  112,
      110,  101,  106,  112,  114,  456,  114,    7,    7,    8,
        8,    8,    8,  111,  116,    8,  453,  114,  116,  123,
      139,  123,    8,  121,  121,  121,  127,  124,  127,  124,
        8,  124,  121,  133,  121,  124,  115,  125,  139,  125,
      121,  132,  133,  132,  180,  125,  133,  136,  180,  136,
      137,  130,  134,  130,    8,    8,    9,    9,    9,    9,
      130,  134,    9,  137,  130,  134,  138,  140,  138,    9,
      147,  148,  147,  148,  149,  174,  153,    9,  452,  167,

      195,  176,  140,  147,  196,  153,  167,  153,  176,  174,
      229,  229,  149,  153,  178,  195,  178,  192,  178,  196,
      384,    9,    9,   10,   10,   10,   10,  178,  154,   10,
      186,  186,  201,  186,  384,  192,   10,  154,  156,  154,
      156,  154,  156,  183,   10,  154,  156,  201,  184,  188,
      188,  226,  183,  156,  183,  226,  156,  184,  450,  184,
      183,  184,  197,  188,  197,  184,  198,  202,   10,   10,
       11,   11,   11,   11,  206,  197,   11,  303,  303,  203,
      208,  449,  202,   11,  198,  207,  211,  212,  216,  206,
       11,   11,   11,   12,   12,   12,   12,  203,  208,   12,

      207,  211,  212,  216,  448,  213,   12,  241,  225,  217,
      225,  305,  305,   12,   12,   12,   14,   14,   14,   14,
      241,   14,   14,  213,  217,  221,  221,  221,  234,   14,
      234,  240,  406,  240,  221,  445,  221,   14,   15,   15,
       15,   15,  221,  304,   15,  223,  406,  223,   15,  223,
      224,   15,  224,  223,  354,  354,  304,  243,  224,   15,
      227,  228,  227,  228,  227,  228,  246,  235,  227,  228,
      230,  231,  230,  231,  230,  243,  235,  444,  230,  231,
      235,  246,  443,   15,   15,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,  233,  236,  233,  247,  298,  423,  253,
      442,  423,  233,  236,  255,  440,  233,  236,  253,  287,
      253,  247,  298,  255,  288,  255,  253,  255,  287,  291,
      287,  255,  439,  288,  293,  288,  287,  288,  291,  299,
      291,  288,  300,  293,  301,  293,  291,  293,  302,  308,
      309,  293,  431,  422,  299,  352,  422,  300,  308,  301,
      308,  343,  308,  302,  345,  309,  308,  385,  352,  422,

      343,  357,  343,  345,  409,  345,  385,  345,  343,  430,
      357,  345,  357,  409,  357,  429,  436,  428,  357,  436,
      427,  426,  425,  424,  421,  420,  419,  417,  416,  415,
      414,  413,  436,  468,  468,  468,  468,  468,  468,  468,
      468,  468,  469,  469,  469,  469,  469,  469,  469,  469,
      469,  470,  470,  470,  470,  470,  470,  470,  470,  470,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  473,  473,
      473,  473,  473,  473,  473,  473,  473,  474,  474,  474,
      474,  474,  474,  474,  474,  474,  475,  475,  475,  475,

      475,  475,  475,  475,  475,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  477,  477,  477,  477,  477,  477,
      477,  477,  477,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  479,  412,  479,  480,  480,  480,  480,  480,
      480,  480,  480,  480,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  482,  482,  411,  482,  482,  482,  482,
      482,  482,  483,  483,  410,  483,  483,  483,  483,  483,
      483,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      485,  485,  408,  485,  485,  485,  485,  485,  485,  486,
      486,  405,  486,  486,  486,  486,  486,  486,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  488,  488,  404,
      488,  488,  488,  488,  488,  488,  489,  489,  403,  489,
      489,  489,  489,  489,  489,  490,  490,  490,  490,  490,
      490,  490,  490,  490,  491,  491,  402,  491,  491,  491,
      491,  491,  491,  492,  492,  401,  492,  492,  492,  492,
      492,  492,  493,  493,  493,  493,  493,  493,  493,  493,
      493,  494,  494,  397,  494,  494,  494,  494,  494,  494,
      495,  495,  395,  495,  495,  495,  495,  495,  495,  496,
      391,  390,  496,  389,  496,  496,  496,  496,  497,  497,
      388,  497,  497,  497,  497,  497,  497,  498,  498,  498,

      498,  498,  498,  498,  498,  498,  499,  499,  387,  499,
      499,  499,  499,  499,  499,  500,  500,  500,  500,  500,
      500,  500,  500,  500,  501,  501,  386,  501,  501,  501,
      501,  501,  501,  502,  383,  502,  503,  503,  382,  503,
      503,  503,  503,  503,  503,  504,  504,  504,  504,  504,
      381,  504,  504,  504,  505,  505,  505,  505,  505,  380,
      505,  505,  505,  506,  506,  506,  506,  506,  379,  506,
      506,  506,  507,  507,  507,  507,  507,  507,  507,  507,
      507,  508,  508,  508,  508,  508,  377,  508,  508,  508,
      509,  376,  375,  374,  372,  371,  370,  509,  510,  369,

      510,  511,  511,  511,  367,  511,  511,  511,  511,  511,
      512,  512,  512,  512,  512,  512,  512,  366,  512,  513,
      513,  513,  513,  513,  513,  513,  513,  513,  363,  362,
      361,  360,  359,  358,  356,  353,  351,  350,  349,  347,
      346,  344,  342,  340,  338,  337,  336,  335,  334,  333,
      332,  331,  330,  327,  326,  324,  323,  321,  320,  318,
      316,  315,  314,  313,  312,  311,  310,  307,  306,  297,
      296,  295,  294,  292,  290,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  268,  267,  266,  265,  264,  263,  262,  261,

      260,  259,  258,  257,  256,  254,  252,  248,  242,  238,
      237,  191,  190,  189,  185,  181,  179,  175,  173,  172,
      171,  170,  169,  168,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  152,  144,   67,   66,   65,   60,
       59,   55,   54,   53,   51,   50,   49,   48,   47,   46,
       43,   41,   40,   34,   25,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 2 "lex.l"
/* $Id: lex.l,v 1.1 2004-05-03 05:17:48 behdad Exp $
 *
 * C manual page generator
 * Lexical analyzer specification
 */

#include <ctype.h>

extern boolean inbasefile;  /* Steven Haehn  Mar 19, 1996 */

static char *cur_file;			/* current file name (malloced) */
int line_num = 1;		/* current line number in file */
static int curly = 0;		/* number of curly brace nesting levels */
static int square = 0;		/* number of square bracket nesting levels */
static int ly_count = 0;	/* number of occurrences of %% */
static int embedded = 0;	/* flag for embedded compiler directives */

/* temporary string buffer */
static char buf[MAX_TEXT_LENGTH];

#define DYNBUF_ALLOC	240	/* size of increment of dynamic buf */
static char *dynbuf;		/* start of dynamic buf */
static int dynbuf_size;		/* number of bytes allocated */
static int dynbuf_current;	/* current end of buffer */

static boolean comment_ateol;	/* does comment start & end at end of a line? */
static boolean comment_remember;/* remember contents of current comment? */
static boolean comment_caller;	/* state we were in before */
static boolean body_start = FALSE; /* At the start of a function body */ 

typedef struct {
#ifdef FLEX_SCANNER
    YY_BUFFER_STATE buffer;
#else
    FILE *fp;
#endif
    char *file;
    int line_num;
} IncludeStack;

static int inc_depth = 0;			/* include nesting level */
static IncludeStack inc_stack[MAX_INC_DEPTH];	/* stack of included files */

static void update_line_num _((void));
static void do_include _((char *filename, int sysinc));
static void new_dynbuf();
static void add_dynbuf _((int c));
static char *return_dynbuf();
static void get_cpp_directive();
static boolean process_line_directive _((const char *new_file));

/*
 * The initial comment processing is done primarily by the rather complex lex
 * rules in the various comment start states, the main functions being removal
 * of leading *'s, /'s and whitespace on a line, the removal of trailing
 * whitespace on a line, and the coalescing of separate comments on adjacent
 * lines.  The remaining bits of textual content are collected by the following
 * functions, which simply strip leading and trailing blank lines.
 */
void start_comment _((boolean ateol));
int end_comment _((boolean ateol));
void add_comment _((const char *s));
void newline_comment _((void));

static int comment_newlines;	/* number of newlines hit in comment */
static boolean comment_started;	/* have preceding empty lines been skipped */

#ifdef FLEX_SCANNER	/* flex uses YY_START instead of YYSTATE */
#define YYSTATE	YY_START
#ifndef YY_START	/* flex 2.3.8 & before didn't support it at all */
#define YY_START ((yy_start - 1) / 2)
#endif
#endif

#undef yywrap	/* for flex */

/* SKIP		skipping value assignment in an enum */
#line 949 "lex.yy.c"

#line 951 "lex.yy.c"

#define INITIAL 0
#define CPP1 1
#define INIT1 2
#define INIT2 3
#define CURLY 4
#define SQUARE 5
#define LEXYACC 6
#define SKIP 7
#define COMMENT 8
#define COMMLINE 9
#define CPPCOMMENT 10
#define EMBEDDED 11

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 92 "lex.l"



#line 1186 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 468 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1156 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 95 "lex.l"
{
			    if (++ly_count >= 2)
				BEGIN INITIAL;
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 99 "lex.l"
BEGIN INITIAL;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 100 "lex.l"
update_line_num();
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "lex.l"
;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 102 "lex.l"
BEGIN LEXYACC;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 104 "lex.l"
BEGIN CPP1;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 106 "lex.l"
{
			    sscanf(yytext, "define %s", buf);
			    get_cpp_directive();
			    new_symbol(typedef_names, buf, DS_EXTERN);
			}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 112 "lex.l"
{
			    sscanf(yytext, "include \"%[^\"]\"", buf);
			    get_cpp_directive();
			    do_include(buf, FALSE);
			}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 117 "lex.l"
{
			    sscanf(yytext, "include <%[^>]>", buf);
			    get_cpp_directive();
			    do_include(buf, TRUE);
			}
	YY_BREAK
case 10:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 123 "lex.l"
{
			    sscanf(yytext, "line %d \"%[^\"]\"",
				    &line_num, buf);
			    --line_num;
			    BEGIN INITIAL;

			    if (process_line_directive(buf))
			        inbasefile = yylval.boolean;
			}
	YY_BREAK
case 11:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 132 "lex.l"
{
			    sscanf(yytext, "%d \"%[^\"]\"", &line_num, buf);
			    --line_num;
			    BEGIN INITIAL;

			    if (process_line_directive(buf))
			        inbasefile = yylval.boolean;
			}
	YY_BREAK
case 12:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 140 "lex.l"
{
			    sscanf(yytext, "%d ", &line_num);
			    --line_num;
			    BEGIN INITIAL;
			}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 146 "lex.l"
get_cpp_directive();
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 148 "lex.l"
return '(';
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 149 "lex.l"
return ')';
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 150 "lex.l"
return '*';
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 151 "lex.l"
{
			    BEGIN INITIAL;	/* stop skipping */
			    return ',';
			}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 155 "lex.l"
return ';';
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 156 "lex.l"
return T_ELLIPSIS;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 157 "lex.l"
{ update_line_num(); return T_STRING_LITERAL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 159 "lex.l"
return T_AUTO;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 160 "lex.l"
return T_EXTERN;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 161 "lex.l"
return T_REGISTER;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 162 "lex.l"
return T_STATIC;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 163 "lex.l"
return T_TYPEDEF;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 164 "lex.l"
return T_CHAR;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 165 "lex.l"
return T_DOUBLE;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 166 "lex.l"
return T_FLOAT;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 167 "lex.l"
return T_INT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 168 "lex.l"
return T_VOID;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 169 "lex.l"
return T_LONG;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 170 "lex.l"
return T_SHORT;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 171 "lex.l"
return T_SIGNED;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 172 "lex.l"
return T_SIGNED;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 173 "lex.l"
return T_SIGNED;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 174 "lex.l"
return T_UNSIGNED;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 175 "lex.l"
{ enum_state = KEYWORD; return T_ENUM; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 176 "lex.l"
return T_STRUCT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 177 "lex.l"
return T_UNION;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 178 "lex.l"
return T_CONST;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 179 "lex.l"
return T_CONST;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 180 "lex.l"
return T_CONST;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 181 "lex.l"
return T_VOLATILE;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 182 "lex.l"
return T_VOLATILE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 183 "lex.l"
return T_VOLATILE;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 184 "lex.l"
return T_INLINE;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 185 "lex.l"
return T_INLINE;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 186 "lex.l"
return T_INLINE;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 187 "lex.l"
return T_CDECL;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 188 "lex.l"
return T_FAR;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 189 "lex.l"
return T_HUGE;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 190 "lex.l"
return T_INTERRUPT;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 191 "lex.l"
return T_NEAR;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 192 "lex.l"
return T_PASCAL;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 193 "lex.l"
;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 195 "lex.l"
{
			    BEGIN EMBEDDED;
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 198 "lex.l"
++embedded;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 199 "lex.l"
{
			    if (--embedded == 0)
				BEGIN INITIAL;
			}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 203 "lex.l"
;
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 204 "lex.l"
update_line_num();
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 206 "lex.l"
{
			    if (enum_state == BRACES)	BEGIN SKIP;
			    yylval.text = strduplicate(yytext);
			    if (is_typedef_name(yytext))
				return T_TYPEDEF_NAME;
			    else
				return T_IDENTIFIER;
			}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 215 "lex.l"
BEGIN INIT1;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 216 "lex.l"
{ curly = 1; BEGIN INIT2; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 217 "lex.l"
{
			    unput(yytext[yyleng-1]);
			    BEGIN INITIAL;
			    return T_INITIALIZER;
			}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 222 "lex.l"
update_line_num();
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 223 "lex.l"
;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 225 "lex.l"
++curly;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 226 "lex.l"
{
			    if (--curly == 0) {
				BEGIN INITIAL;
				return T_INITIALIZER;
			    }
			}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 232 "lex.l"
update_line_num();
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 233 "lex.l"
;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 235 "lex.l"
{
			    if (enum_state == KEYWORD)
			    {
				enum_state = BRACES;
				return '{';
			    }
			    else
			    {
				curly = 1;
				BEGIN CURLY;
				body_start = TRUE; /* Look for first comment
						    * in the func body.
						    */
				safe_free(body_comment);
				body_comment = NULL;
			    }
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 252 "lex.l"
{
 			    BEGIN INITIAL;	/* stop skipping */
			    return '}';
			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 257 "lex.l"
++curly;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 258 "lex.l"
{
			    if (--curly == 0) {
				BEGIN INITIAL;
				return T_BRACES;
			    }
			}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 264 "lex.l"
update_line_num();
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 265 "lex.l"
body_start = FALSE;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 267 "lex.l"
{
			  new_dynbuf(); add_dynbuf(yytext[0]);
			  square = 1; BEGIN SQUARE;
			}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 271 "lex.l"
{ ++square; add_dynbuf(yytext[0]); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 272 "lex.l"
{
			    add_dynbuf(yytext[0]);
			    if (--square == 0) {
				BEGIN INITIAL;
				yylval.text = return_dynbuf();
				return T_BRACKETS;
			    }
			}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 280 "lex.l"
{
			    int i;
			    for (i = 0; i < yyleng; ++i)
			    {
				if (yytext[i] == '\n') ++line_num;
				add_dynbuf(yytext[i]);
			    }
			}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 289 "lex.l"
{
				comment_caller = YYSTATE;
				start_comment(FALSE);
				BEGIN COMMENT; }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 293 "lex.l"
{
				yyless(yyleng-1);
				comment_caller = YYSTATE;
				start_comment(FALSE);
				BEGIN COMMENT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 298 "lex.l"
{
				comment_caller = YYSTATE;
				start_comment(TRUE);
				BEGIN COMMENT; }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 302 "lex.l"
{
				yyless(yyleng-1);
				comment_caller = YYSTATE;
				start_comment(TRUE);
				BEGIN COMMENT; }
	YY_BREAK
case 85:
#line 308 "lex.l"
case 86:
YY_RULE_SETUP
#line 308 "lex.l"
BEGIN COMMENT;
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 309 "lex.l"
{ yyless(yyleng-1); BEGIN COMMENT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 310 "lex.l"
{ yyless(0); BEGIN COMMENT; }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 311 "lex.l"
newline_comment();
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 312 "lex.l"
newline_comment();
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 313 "lex.l"
{
				yyless(yyleng-1); newline_comment(); }
	YY_BREAK
case 92:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 315 "lex.l"
{ int ret = end_comment(TRUE);
				  BEGIN comment_caller;
				  if (ret)	return ret; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 318 "lex.l"
{ int ret = end_comment(FALSE);
				  BEGIN comment_caller;
				  if (ret)	return ret; }
	YY_BREAK
case 94:
#line 322 "lex.l"
case 95:
#line 323 "lex.l"
case 96:
YY_RULE_SETUP
#line 323 "lex.l"
add_comment(yytext);
	YY_BREAK
case 97:
/* rule 97 can match eol */
YY_RULE_SETUP
#line 324 "lex.l"
{ newline_comment(); BEGIN COMMLINE; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 326 "lex.l"
{
				comment_caller = YYSTATE;
				start_comment(FALSE);
				BEGIN CPPCOMMENT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 330 "lex.l"
{
				comment_caller = YYSTATE;
				start_comment(TRUE);
				BEGIN CPPCOMMENT; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 334 "lex.l"
add_comment(yytext);
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 335 "lex.l"
newline_comment();
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 336 "lex.l"
{ int ret = end_comment(TRUE);
				  ++line_num;
				  BEGIN comment_caller;
				  if (ret)	return ret; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 341 "lex.l"
;
	YY_BREAK
case 104:
/* rule 104 can match eol */
YY_RULE_SETUP
#line 342 "lex.l"
++line_num;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 344 "lex.l"
{
			    output_error();
			    fprintf(stderr, "bad character '%c'\n", yytext[0]);
			}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 348 "lex.l"
ECHO;
	YY_BREAK
#line 1926 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CPP1):
case YY_STATE_EOF(INIT1):
case YY_STATE_EOF(INIT2):
case YY_STATE_EOF(CURLY):
case YY_STATE_EOF(SQUARE):
case YY_STATE_EOF(LEXYACC):
case YY_STATE_EOF(SKIP):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(COMMLINE):
case YY_STATE_EOF(CPPCOMMENT):
case YY_STATE_EOF(EMBEDDED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 468 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 468 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 467);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 348 "lex.l"


/* If the matched text contains any new line characters, then update the
 * current line number.
 */
static void
update_line_num ()
{
    const char *p = (const char *)yytext;
    while (*p != '\0') {
	if (*p++ == '\n')
	    line_num++;
    }
}

void start_comment(ateol)
boolean ateol;	/* does comment start at end of an existing line? */
{
    comment_remember =	(look_at_body_start && body_start) ||
		    ((comment_caller == INITIAL || comment_caller == SKIP) &&
			(inbasefile || enum_state == BRACES));

    if (comment_remember)
    {
	comment_ateol = ateol;
	comment_newlines = 0;
	comment_started = FALSE;
	new_dynbuf();
    }
}

int end_comment(ateol)
boolean ateol;	/* does comment end at end of line? */
{
    if (comment_remember)
    {
	if (!ateol)	comment_ateol = FALSE;
	yylval.text = return_dynbuf();
	if (yylval.text[0] == '\0' ||
	    /* ignore lint directives entirely */
	    strcmp("EMPTY",       yylval.text) == 0 ||
	    strcmp("FALLTHROUGH", yylval.text) == 0 ||
	    strcmp("FALLTHRU",    yylval.text) == 0 ||
	    strcmp("LINTED",      yylval.text) == 0 ||
	    strcmp("LINTLIBRARY", yylval.text) == 0 ||
	    strcmp("LINTSTDLIB",  yylval.text) == 0 ||
	    strcmp("NOTDEFINED",  yylval.text) == 0 ||
	    strcmp("NOTREACHED",  yylval.text) == 0 ||
	    strcmp("NOTUSED",     yylval.text) == 0 ||
	    strncmp("ARGSUSED",   yylval.text,  8) == 0 ||
	    strncmp("PRINTFLIKE", yylval.text, 10) == 0 ||
	    strncmp("SCANFLIKE",  yylval.text,  9) == 0 ||
	    strncmp("VARARGS",    yylval.text,  7) == 0)
	{
	    free(yylval.text);
	    return 0;
	}
	if (body_start) {	/* first comment at start of func body */
	  safe_free(body_comment);
	  body_comment = yylval.text;
	  body_start = FALSE;
	  return 0;
	}
#ifdef DEBUG
	fprintf(stderr,"`%s'\n", yylval.text);
#endif
	return comment_ateol ? T_EOLCOMMENT : T_COMMENT;
    }
    return 0;
}

/* add a newline to the comment, deferring to remove trailing ones */
void newline_comment()
{
    ++line_num;

    if (!comment_remember || !comment_started)	return;

    comment_newlines++;
}

/* add some true text to the comment */
void add_comment(s)
const char *s;
{
#ifdef DEBUG
    fprintf(stderr,"`%s'\n", s);
#endif
    if (!comment_remember)	return;

    comment_started = TRUE;

    while (comment_newlines)
    {
	add_dynbuf('\n');
	comment_newlines--;
    }

    while(*s)
	add_dynbuf(*s++);
}

/* Scan rest of preprocessor statement.
 */
static void
get_cpp_directive ()
{
    int c, lastc = '\0';

    while ((c = input()) > 0) {
	switch (c) {
	case '\n':
	    if (lastc != '\\') {
		unput(c);
		BEGIN INITIAL;
		return;
	    }
	    line_num++;
	    break;
	case '*':
	    if (lastc == '/')
	    {
		/* might be able to attach comments to #defines one day */
		comment_caller = YYSTATE;
		start_comment(TRUE);
		BEGIN COMMENT;
	    }
	    break;
	case '/':
	    if (lastc == '/')
	    {
		/* might be able to attach comments to #defines one day */
		comment_caller = YYSTATE;
		start_comment(TRUE);
		BEGIN CPPCOMMENT;
	    }
	    break;
	}
	lastc = c;
    }
}

/* Process include directive.
 */
static void
do_include (filename, sysinc)
char *filename;		/* file name */
int sysinc;		/* 1 = do not search current directory */
{
    char path[MAX_TEXT_LENGTH];
    int i;
    FILE *fp;
    IncludeStack *sp;

    if (inc_depth >= MAX_INC_DEPTH) {
	output_error();
	fprintf(stderr, "includes too deeply nested\n");
	return;
    }

    for (i = sysinc != 0; i < num_inc_dir; ++i) {
	 strcpy(path, inc_dir[i]);
	 strcat(path, filename);
	 if ((fp = fopen(path, "r")) != NULL) {
	     sp = inc_stack + inc_depth;
	     sp->file = cur_file;
	     sp->line_num = line_num;
#ifdef FLEX_SCANNER
	     sp->buffer = YY_CURRENT_BUFFER;
	     yy_switch_to_buffer(yy_create_buffer(fp, YY_BUF_SIZE));
#else
	     sp->fp = yyin;
	     yyin = fp;
#endif
	     ++inc_depth;
	     cur_file = strduplicate(filename);
	     line_num = 0;
	     return;
	 }
    }
}

/* returns TRUE if the basefile status has changed */
static boolean process_line_directive(new_file)
const char *new_file;
{
    boolean new_stdin;

    /* strip leading ./ that Sun acc prepends */
    if (!strncmp(new_file,"./",2))
	new_file += 2;

    new_stdin = new_file[0] == '\0' || !strcmp(new_file,"stdin");

    /* return BASEFILE token only when file changes */
    if ((cur_file == NULL && !new_stdin) ||
	(cur_file != NULL &&strcmp(cur_file, new_file)))
    {
	safe_free(cur_file);
	cur_file = new_stdin ? NULL : strduplicate(new_file);
	yylval.boolean = basefile ? !strcmp(cur_file,basefile) :
				    cur_file == basefile;
	return TRUE;
    }
    return FALSE;
}

/* When the end of the current input file is reached, pop any
 * nested includes.
 */
int
yywrap ()
{
    IncludeStack *sp;

    if (inc_depth > 0) {
	--inc_depth;
	sp = inc_stack + inc_depth;
	fclose(yyin);
#ifdef FLEX_SCANNER
	yy_delete_buffer(YY_CURRENT_BUFFER);
	yy_switch_to_buffer(sp->buffer);
#else
	yyin = sp->fp;
#endif
	safe_free(cur_file);
	cur_file = sp->file;
	line_num = sp->line_num + 1;
	return 0;
    } else {
	return 1;
    }
}


static void new_dynbuf()
{
    if ((dynbuf = malloc(dynbuf_size = DYNBUF_ALLOC)) == 0)
	outmem();
	
    dynbuf_current = 0;
}

static void add_dynbuf(c)
int c;
{
    if (dynbuf_current == dynbuf_size &&
	((dynbuf = realloc(dynbuf,dynbuf_size += DYNBUF_ALLOC)) == 0))
	    outmem();
	
    dynbuf[dynbuf_current++] = c;
}

static char *return_dynbuf()
{
    add_dynbuf('\0');

    /* chop it back to size */
    if ((dynbuf = realloc(dynbuf,dynbuf_current)) == 0)
	outmem();

    return dynbuf;	
}

/* Output an error message along with the current line number in the
 * source file.
 */
void
output_error ()
{
    errors++;
    fprintf(stderr, "%s:%d: ", cur_file ? cur_file : "stdin", line_num);
    fprintf(stderr, "\n(%s) ", yytext);
}

